version:  "3.8"
services:
  pharmacy-recommendation-database:
    container_name: campus-tadaktadak-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: f431f2c54069/campus-tadaktadak-database
    environment:
      - MARIADB_DATABASE=tadaktadak-campus
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
    #      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
