# ?? app??? ? ?? ??? default? ? ? ??
spring:
  profiles:
    active: local # default
    group:  # group?? ??
      local:
        - common
      prod:
        - common
---
# ???? ??? ???
spring:
  config:
    activate:
      on-profile: common
---
# local?? ??? ???
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/campus-tadaktadak
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
---
# ?? ? ??? ???
spring:
  config:
    activate:
      on-profile: prod
